- name: Update cache and upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
    upgrade_extra_args: --noconfirm
  become: true
  tags:
    - pre-install

- name: Create Development folder
  ansible.builtin.file:
    path: /home/{{ user_name }}/Development
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  become: true

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/guifrrs/dotfiles
    dest: /home/{{ user_name }}/dotfiles
    update: true
  tags:
    - base

- name: Install base packages
  community.general.pacman:
    name: "{{ base }}"
    state: present
  become: true
  tags:
    - base

- name: Include zsh task
  ansible.builtin.include_tasks:
    file: zsh.yml

- name: Include paru task
  ansible.builtin.include_tasks:
    file: paru.yml
